# Generated by Django 4.0.6 on 2022-07-29 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_category_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 29), null=True),
        ),
    ]
