# Generated by Django 4.0.6 on 2022-07-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
